### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [sfrieson/Guac-A-Mole#2]
Steven,

Great job. I had a lot of fun trying to Guac the moles! Your code looks great too, nice use of Object Oriented programming. One thing I will point out is general convention is to call the .prototype attribute each time you add a new method. This is just to make it easier than having to edit a large object and because prototypes are immediately accessible when they are instantiated. Javascript does what is known as lazy evaluation, that is to say if you call a method that hasn't been defined yet inside another Object method, it won't matter as long as you do create the method later. For example: 

``` js
function Test(){}

Test.prototype.thing = function(){
    this.sup()
}

Test.prototype.sup = function(){
   console.log('sup')
}

```

Also, what led you to use Strict Mode? 

Overall great job and great work.

**Comment by ajhofferber** [comment]
Hey Steven!

Great work on your project. Taking a peek into your scripts, it's clear that you had a really good handle on the logic you were building. Your code is broken out well and your use of comments makes it really clear to an observer what each piece of code is responsible for. I also really appreciate your use of jquery animations to make the UI much more fun and interesting!

Overall, some really great stuff! Also, I am really bad at it and couldn't even get through the second level. So there's that. :)

Score: 3 (refer to project 1 markdown for scoring rubric)

-Ash

**Comment by sfrieson** [comment]
Mainly to stop my linter form yelling at me.  But I've seen some positives
of using string mode, like not accidentally calling making two different
variables ( var meant = 5;  ment +=2; )  I know there are some other
positives as well as things that get a little trickier with it on, but
generally I am  more comfortable with rules.
